services:
  backend:
    command: uvicorn config.asgi:application --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  frontend:
    command: npm run dev
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    ports:
      - "3000:3000"

  celery:
    volumes:
      - ./backend:/app

  celery-beat:
    volumes:
      - ./backend:/app

volumes:
  frontend_node_modules:
