# Generated by Django 5.2.3 on 2026-05-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_seed_core_rbac'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_model_n_3fb686_idx',
            old_name='core_audit_model_n_1b2e72_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_user_id_2ff9b7_idx',
            old_name='core_audit_user_id_72dc45_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='core_auditl_created_dc23ea_idx',
            old_name='core_audit_created_5fd3a0_idx',
        ),
        migrations.RenameIndex(
            model_name='otpcode',
            new_name='core_otpcod_phone_b60aed_idx',
            old_name='core_otpcode_phone_4e580e_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
    ]
